### ISSUE TITLE
Nil pointer error appears at v0.14.0 

### ISSUE THREAD

**Issue by onyanko-pon** [fujiwara/lambroll#275]
Hello @fujiwara, thanks for the great tool.
I found a error when exec `lambda init`.

## Error
Nil pointer error appears using new version lambroll when execute `lambroll init` without exacting lambda func.

```bash
$ lambrall version
lambroll v0.14.0
$ lambroll init --function-name=testFunction
2022/11/30 01:15:06 [info] lambroll v0.14.0 with function.json
2022/11/30 01:15:08 [info] function testFunction is not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x198d794]

goroutine 1 [running]:
github.com/fujiwara/lambroll.newFunctionFrom(0xc00083f758, 0x0, 0x0)
        github.com/fujiwara/lambroll/lambroll.go:257 +0x214
github.com/fujiwara/lambroll.(*App).Init(0xc000091040, {0xc000511e40?, 0xc00060c60f?})
        github.com/fujiwara/lambroll/init.go:73 +0x4f5
main._main()
        github.com/fujiwara/lambroll/cmd/lambroll/main.go:146 +0x58b3
main.main()
        github.com/fujiwara/lambroll/cmd/lambroll/main.go:19 +0x19
```

But no error appears using v0.13.0.
```bash
$ lambrall version
lambroll v0.13.0
$ lambroll init --function-name=testFunction
2022/11/30 01:51:22 [info] lambroll v0.13.0 with function.json
2022/11/30 01:51:23 [info] function testFunction is not found
2022/11/30 01:51:24 [info] creating .lambdaignore
2022/11/30 01:51:24 [info] creating function.json
Overwrite existing file function.json? (y/n) [n]: n
2022/11/30 01:51:28 [info] completed
```

## Environment
lambroll version: v0.14.0
OS: macOS monterey 12.3.1

**Comment by fujiwara** [comment]
@onyanko-pon Thank you for reporting!

I found a cause of the panic. fixed by #276.

v0.14.1 released. https://github.com/fujiwara/lambroll/releases/tag/v0.14.1
